spring:
  devtools:
    livereload:
      enabled: true
  thymeleaf:
        cache: false
  
  datasource:
        url: "jdbc:mariadb://localhost:3306/dayary"
        username: root
        password: root
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true

server:
  port: 7777
